# -*- coding: utf-8 -*-
"""GinareaCalc

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gNWlut5rRbj3Ds3y5eABfaTC6QAO_FRl
"""

import streamlit as st
import pandas as pd
import numpy as np

# --- Настройка страницы ---
st.set_page_config(
    page_title="Калькулятор DCA",
    page_icon="📈",
    layout="wide"
)

# --- Заголовок ---
st.title("📈 Калькулятор сеточной DCA-стратегии")

# --- Боковая панель для ручного ввода ---
with st.sidebar:
    st.header("⚙️ Параметры стратегии")

    # --- Поля для ввода данных ---
    initial_order_size = st.number_input("Начальный ордер ($)", min_value=0.1, value=10.0, step=1.0)
    safety_order_size = st.number_input("Страховочный ордер ($)", min_value=0.1, value=10.0, step=1.0)
    safety_orders_count = st.number_input("Max trigger number", min_value=1, value=20, step=1)
    price_step_percent = st.number_input("Grid step (%)", min_value=0.1, value=1.0, step=0.1)
    price_step_multiplier = st.number_input("Grid step ratio (%)", min_value=0.1, value=1.5, step=0.1)

# --- Основная часть: Расчеты и вывод ---
if st.sidebar.button("🚀 Рассчитать сетку"):
    # --- Логика расчетов ---
    price_step = price_step_percent / 100.0
    order_sizes = [safety_order_size] * safety_orders_count

    price_deviations = []
    current_step = price_step
    for _ in range(safety_orders_count):
        price_deviations.append(current_step)
        current_step *= price_step_multiplier

    required_deposit = initial_order_size + sum(order_sizes)
    trading_range_sum = sum(price_deviations) * 100

    # --- Вывод ключевых показателей ---
    st.header("📊 Ключевые показатели стратегии")
    col1, col2 = st.columns(2)
    with col1:
        st.markdown(f"""
        <div style="border: 1px solid #262730; border-radius: 0.25rem; padding: 1rem;">
            <div style="font-size: 0.8rem; color: #808495;">Требуемый депозит</div>
            <div style="font-size: 1.5rem; color: #28a745; font-weight: bold;">${required_deposit:,.2f}</div>
        </div>
        """, unsafe_allow_html=True)
    with col2:
        st.markdown(f"""
        <div style="border: 1px solid #262730; border-radius: 0.25rem; padding: 1rem;">
            <div style="font-size: 0.8rem; color: #808495;">Итоговый Trading Range</div>
            <div style="font-size: 1.5rem; color: #28a745; font-weight: bold;">{trading_range_sum:,.2f}%</div>
        </div>
        """, unsafe_allow_html=True)

    # --- Формирование и вывод детальной таблицы ---
    st.header("📋 Детальная таблица сетки ордеров")

    order_data_list = []
    cumulative_volume = initial_order_size
    cumulative_range = 0.0
    for i in range(safety_orders_count):
        cumulative_volume += order_sizes[i]
        cumulative_range += price_deviations[i] * 100
        order_data_list.append({
            '№ ордера': str(i + 1),
            'Размер ордера ($)': order_sizes[i],
            'Отклонение цены (%)': price_deviations[i] * 100,
            'Суммарный объем ($)': cumulative_volume,
            'Trading Range (%)': cumulative_range
        })
    order_data_list.insert(0, {
        '№ ордера': 'Начальный',
        'Размер ордера ($)': initial_order_size,
        'Отклонение цены (%)': 0.0,
        'Суммарный объем ($)': initial_order_size,
        'Trading Range (%)': 0.0
    })
    full_grid_df = pd.DataFrame(order_data_list).set_index('№ ордера')

    st.dataframe(full_grid_df.style.format({
        'Размер ордера ($)': '${:,.2f}',
        'Отклонение цены (%)': '{:,.2f}%',
        'Суммарный объем ($)': '${:,.2f}',
        'Trading Range (%)': '{:,.2f}%'
    }))

else:
    st.info("Задайте параметры в боковой панели, затем нажмите 'Рассчитать сетку'.")