# -*- coding: utf-8 -*-
"""GinareaCalc

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gNWlut5rRbj3Ds3y5eABfaTC6QAO_FRl
"""

import streamlit as st
import pandas as pd
import numpy as np

# --- Настройка страницы ---
st.set_page_config(
    page_title="Калькулятор DCA",
    page_icon="📈",
    layout="wide"
)

# --- БАЗА ДАННЫХ: БИРЖИ И МОНЕТЫ ---
PRESETS = {
    "Binance": {
        "BTC": {"min_grid_step": 0.2, "min_order_size": 10.0},
        "ETH": {"min_grid_step": 0.25, "min_order_size": 10.0},
        "BNB": {"min_grid_step": 0.3, "min_order_size": 5.0},
        "SOL": {"min_grid_step": 0.5, "min_order_size": 5.0},
    },
    "Bybit": {
        "BTC": {"min_grid_step": 0.2, "min_order_size": 5.0},
        "ETH": {"min_grid_step": 0.25, "min_order_size": 5.0},
        "SOL": {"min_grid_step": 0.5, "min_order_size": 2.0},
        "XRP": {"min_grid_step": 0.5, "min_order_size": 1.0},
        "LTC": {"min_grid_step": 0.4, "min_order_size": 3.0},
    },
    "OKX": {
        "BTC": {"min_grid_step": 0.2, "min_order_size": 5.0},
        "ETH": {"min_grid_step": 0.25, "min_order_size": 5.0},
        "DOT": {"min_grid_step": 0.7, "min_order_size": 1.0},
        "LINK": {"min_grid_step": 0.5, "min_order_size": 2.0},
    },
    # --- ВОТ ВАША НОВАЯ БИРЖА ---
    "BMEX": {
        "BTC": {"min_grid_step": 0.15, "min_order_size": 1.0},
        "ETH": {"min_grid_step": 0.20, "min_order_size": 1.0},
        "SOL": {"min_grid_step": 0.4, "min_order_size": 1.0},
    }
}

# --- Заголовок ---
st.title("📈 Калькулятор сеточной DCA-стратегии")

# --- Боковая панель ---
with st.sidebar:
    st.header("⚙️ Параметры стратегии")

    # --- Выбор биржи (теперь с BMEX) ---
    exchange_selection = st.selectbox(
        "1. Выберите биржу:",
        sorted(list(PRESETS.keys())) # Сортируем биржи по алфавиту
    )

    available_coins = list(PRESETS[exchange_selection].keys())
    coin_selection = st.selectbox(
        "2. Выберите монету (или 'Ручной'):",
        ['Ручной'] + sorted(available_coins)
    )

    if coin_selection != 'Ручной':
        preset = PRESETS[exchange_selection][coin_selection]
        default_grid_step = preset["min_grid_step"]
        default_order_size = preset["min_order_size"]
        st.info(f"Для {coin_selection} на {exchange_selection} применены мин. значения.")
    else:
        default_grid_step = 1.0
        default_order_size = 10.0

    initial_order_size = st.number_input("Начальный ордер ($)", min_value=0.1, value=default_order_size, step=1.0)
    safety_order_size = st.number_input("Страховочный ордер ($)", min_value=0.1, value=default_order_size, step=1.0)
    safety_orders_count = st.number_input("Max trigger number", min_value=1, value=20, step=1)
    price_step_percent = st.number_input("Grid step (%)", min_value=0.1, value=default_grid_step, step=0.1)
    price_step_multiplier = st.number_input("Grid step ratio (%)", min_value=0.1, value=1.5, step=0.1)

# --- Основная часть (код расчетов и вывода остался без изменений) ---
if st.sidebar.button("🚀 Рассчитать сетку"):
    # ... (весь код расчетов и вывода остается прежним) ...
    price_step = price_step_percent / 100.0
    order_sizes = [safety_order_size] * safety_orders_count
    price_deviations = []
    current_step = price_step
    for _ in range(safety_orders_count):
        price_deviations.append(current_step)
        current_step *= price_step_multiplier
    required_deposit = initial_order_size + sum(order_sizes)
    trading_range_sum = sum(price_deviations) * 100

    st.header("📊 Ключевые показатели стратегии")
    col1, col2 = st.columns(2)
    with col1:
        st.markdown(f"""
        <div style="border: 1px solid #262730; border-radius: 0.25rem; padding: 1rem;">
            <div style="font-size: 0.8rem; color: #808495;">Требуемый депозит</div>
            <div style="font-size: 1.5rem; color: #28a745; font-weight: bold;">${required_deposit:,.2f}</div>
        </div>
        """, unsafe_allow_html=True)
    with col2:
        st.markdown(f"""
        <div style="border: 1px solid #262730; border-radius: 0.25rem; padding: 1rem;">
            <div style="font-size: 0.8rem; color: #808495;">Итоговый Trading Range</div>
            <div style="font-size: 1.5rem; color: #28a745; font-weight: bold;">{trading_range_sum:,.2f}%</div>
        </div>
        """, unsafe_allow_html=True)

    st.header("📋 Детальная таблица сетки ордеров")
    order_data_list = []
    cumulative_volume = initial_order_size
    cumulative_range = 0.0
    for i in range(safety_orders_count):
        cumulative_volume += order_sizes[i]
        cumulative_range += price_deviations[i] * 100
        order_data_list.append({
            '№ ордера': str(i + 1),
            'Размер ордера ($)': order_sizes[i],
            'Отклонение цены (%)': price_deviations[i] * 100,
            'Суммарный объем ($)': cumulative_volume,
            'Trading Range (%)': cumulative_range
        })
    order_data_list.insert(0, {
        '№ ордера': 'Начальный',
        'Размер ордера ($)': initial_order_size,
        'Отклонение цены (%)': 0.0,
        'Суммарный объем ($)': initial_order_size,
        'Trading Range (%)': 0.0
    })
    full_grid_df = pd.DataFrame(order_data_list).set_index('№ ордера')
    st.dataframe(full_grid_df.style.format({
        'Размер ордера ($)': '${:,.2f}',
        'Отклонение цены (%)': '{:,.2f}%',
        'Суммарный объем ($)': '${:,.2f}',
        'Trading Range (%)': '{:,.2f}%'
    }))

else:
    st.info("Выберите биржу и монету или задайте параметры вручную, затем нажмите 'Рассчитать сетку'.")